apiVersion: v1
kind: Namespace
metadata:
  name: amazon-cloudwatch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: amazon-cloudwatch
  annotations:
    # 1-2 단계에서 생성한 IAM 역할 ARN을 여기에 연결합니다.
    eks.amazonaws.com/role-arn: "arn:aws:iam::646558765106:role/EKS-Fluent-Bit-Role"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
  # Fluent Bit가 Pod와 Namespace 정보를 읽을 수 있도록 허용합니다.
  - apiGroups: [""]
    resources:
      - "namespaces"
      - "pods"
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: amazon-cloudwatch
